# Generated by Django 5.1.2 on 2024-11-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_alter_post_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='legal_status',
            field=models.CharField(choices=[('sổ đỏ/sổ hồng', 'Sổ đỏ/Sổ hồng'), ('chưa có', 'Chưa có'), ('khác', 'Khác')], max_length=50),
        ),
    ]
