# Generated by Django 5.1.3 on 2024-12-02 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_alter_post_legal_status'),
        ('application', '0028_merge_20241201_1028'),
    ]

    operations = [
    ]
